# Thanks to https://github.com/2creatives/vagrant-centos/

# Remove old kernels. This can't be run in %post of the minimal ISO kickstart as
# it will error thinking it's the running kernel
package-cleanup --oldkernels --count=1 -y
# Cleanup temporary yum files / caches
yum -y clean all

# https://github.com/CentOS/ImageStandards
# "No udev rules from the image build node should be present."
# I think all the hardware specific rules generated by the installer are 70-
rm -f /etc/udev/rules.d/70-*.rules

# ".bash_history should be empty in all accounts."
awk -F: '{ print $6 }' /etc/passwd | while read home_directory; do
  bash_history_file="${home_directory}/.bash_history"
  [ -f "${bash_history_file}" ] && rm -f "${bash_history_file}"
done

# Remove HWADDR and UUID from network configuration
sed -i /HWADDR/d /etc/sysconfig/network-scripts/ifcfg-eth0
sed -i /UUID/d /etc/sysconfig/network-scripts/ifcfg-eth0

# Remove VBoxGuestAdditions ISO
vbox_version="$(cat /home/${SUDO_USER}/.vbox_version)"
rm -f /home/${SUDO_USER}/VBoxGuestAdditions_${vbox_version}.iso

# Stop services that log before clearing logs
service postfix stop
service rsyslog stop
# Clear logs
rm -f \
  /var/log/anaconda.ifcfg.log \
  /var/log/anaconda.log \
  /var/log/anaconda.program.log \
  /var/log/anaconda.storage.log \
  /var/log/anaconda.syslog \
  /var/log/anaconda.yum.log \
  /root/anaconda-ks.cfg \
  /root/install.log \
  /root/install.log.syslog
echo -n | tee \
  /var/log/cron \
  /var/log/dmesg \
  /var/log/dracut.log \
  /var/log/lastlog \
  /var/log/maillog \
  /var/log/messages \
  /var/log/secure \
  /var/log/wtmp \
  /var/log/yum.log

# Clear tmp
rm -rf /tmp/* /tmp/.[^.]+

# Host SSH keys are deleted by overloading :shutdown_cmd as part of
# definition.rb, which happens when the VM is exported with veewee vbox export:
# This comment is just to show what is effectively happening
# rm -f /etc/ssh/ssh_host*

# A number of these will fail depending on if the scripts are included or not
rm -f /home/${SUDO_USER}/ansible.sh
rm -f /home/${SUDO_USER}/authorized_keys_ec2.sh
rm -f /home/${SUDO_USER}/puppet.sh
rm -f /home/${SUDO_USER}/vagrant.sh
rm -f /home/${SUDO_USER}/virtualbox.sh
rm -f /home/${SUDO_USER}/zerodisk.sh

# Delete the cleanup script
rm -f /home/${SUDO_USER}/cleanup.sh
